default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails-my-to-do_development

test:
  <<: *default
  database: rails-my-to-do_test

production:
  <<: *default
  database: rails_my_to_do_production
  username: rails_my_to_do
  password: <%= ENV["RAILS_MY_TO_DO_DATABASE_PASSWORD"] %>
